[package]
name = "appimage_updater"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
rayon = "1.5"
clap = { version = "4.0", features = ["derive"] }
colored = "2.0"

[build-dependencies]
chrono = "0.4.38"
