# Rust Toolchain File

# Version of Rust to use
[toolchain]
channel = "stable"

# Run `rustup target add <target>` to install a target platform
[target]
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu"
]
